sonar.projectKey=safe-zone
sonar.projectName=safe-zone

sonar.sources=user_service/src/main,product_service/src/main,gateway_service/src/main,media_service/src/main,client/src

sonar.tests=user_service/src/test,product_service/src/test,gateway_service/src/test,media_service/src/test,client/src

sonar.java.binaries=user_service/target/classes,product_service/target/classes,gateway_service/target/classes,media_service/target/classes

sonar.coverage.jacoco.xmlReportPaths=user_service/target/site/jacoco/jacoco.xml,product_service/target/site/jacoco/jacoco.xml,gateway_service/target/site/jacoco/jacoco.xml,media_service/target/site/jacoco/jacoco.xml

sonar.javascript.lcov.reportPaths=client/coverage/**/lcov.info

sonar.sourceEncoding=UTF-8